### PR TITLE
Workshop Checkin Upgrade

### PR DESCRIPTION
**Pull request by chacha**
In order to improve the workshop checkin process, Garrison and I have identified a plan for addressing some of the key issues we've found during the 2015-2016 year. This would be a great project for our programming team, and has a lot of potential for growth and integration with things like Hubot and the website.

Please read the project proposal and give feedback. Also, if anyone is particularly interested in taking over this project, please let me know. Thanks!

### CODE REVIEW

**Comment by bobron** [comment]
I really like the idea, and I think i might want to tackle the project. Should I just start researching now?

**Comment by chacha** [comment]
@bobron I think this would be a great project for you to take on. I have a couple idea for making the actual terminal(s) come together, but we should talk about it soon.

**Comment by multiplemonomials** [comment]
I'd like to work on this too.  I think that the biggest question is what language to implement it in.  The scanner looks like a keyboard, so we just need to read it as one.  Loos like that's doable with Linux's C API. 

http://www.thelinuxdaily.com/2010/05/grab-raw-keyboard-input-from-event-device-node-devinputevent/

We don't have to buy a Raspberry Pi, we can just use the Beaglebone we already have.

**Comment by chacha** [comment]
@multiplemonomials What languages does the Beaglebone use? If we could make all of this Java across the board, it would make it easier for future team members to modify and hack on.

**Comment by bobron** [comment]
The beaglebone is like the Rasberry Pi as it runs Linux. We could do it in Java, but having a barcode scanner input might take some time.

**Comment by chacha** [comment]
But isn’t there already Java-based code on the Attendance-Scanner tablet to do it? If its just a keyboard, you aren’t really doing anything in terms of image recognition.

**Comment by bobron** [comment]
I lied. The Java awt package has native key listeners that should work for us.

**Comment by multiplemonomials** [comment]
Yeah, but Android has a Java API for accessing the keyboard.  In Linux, this API only exists in C.  We would need to find or write a native library which calls from Java to C.

It would be a lot easier to write this in C++.

**Comment by bobron** [comment]
@multiplemonomials: I might be wrong, but in Java 7 a KeyListener package was added.

**Comment by multiplemonomials** [comment]
Yeah, but that's a java AWT class.  It's for writing windowed apps.  We need this to read input from the keyboard when no window is open and there is no GUI environment.

**Comment by bobron** [comment]
Can we move this to the programming channel of slack?

**Comment by chacha** [comment]
You can, but once you've figured out a direction, please report the
conclusion to this issue.

**Comment by multiplemonomials** [comment]
Actually, it looks like it might be possible to do this from Java by reading the device-file and extracting the `code` member from [this thing](https://www.kernel.org/doc/htmldocs/device-drivers/API-input-event.html).

But it would still be a pain.  I say use C++.

**Pull request closed without merging**
